# -*- coding: utf-8 -*-
"""week4_ml.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16tmRVvJCHitW8pJ8tjACs53yJQuTQh_U

**Naive Bayes Theorem**

Gaussian Model
"""

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.datasets import load_wine
from sklearn.metrics import precision_recall_curve
import pandas as pd

wine = load_wine()
x = wine.data
y = wine.target
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 0)

gas = GaussianNB().fit(x_train, y_train)

print("Train", gas.score(x_train, y_train))
print("Test", gas.score(x_test, y_test))