# -*- coding: utf-8 -*-
"""text_mining_week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14KXjyt307kcSZ0UTiL1mhnIxr-StzstZ

Python Text Basics(Part 1)
"""

s = "Ethics or moral philosophy is a branch of philosophy that involves systematizing, defending, and recommending concepts of right and wrong behavior. The field of ethics, along with aesthetics, concerns matters of value, and thus comprises the branch of philosophy called axiology."

# length of text
print(len(s))

# tokenization
sr = s.split(' ')
print(sr)

# long words(with with more than 3 letters)
print([i for i in sr if len(i) > 3])

# words that start with a capital letter
print([i for i in sr if i.istitle()])

# words that end with  g
print([i for i in sr if i.endswith('g')])