# -*- coding: utf-8 -*-
"""text_mining_week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14KXjyt307kcSZ0UTiL1mhnIxr-StzstZ

Python Text Basics(Part 1)
"""

s = "Ethics or moral philosophy is a branch of philosophy that involves systematizing, defending, and recommending concepts of right and wrong behavior. The field of ethics, along with aesthetics, concerns matters of value, and thus comprises the branch of philosophy called axiology."

# length of text
print(len(s))

# tokenization
sr = s.split(' ')
print(sr)

# long words(with with more than 3 letters)
print([i for i in sr if len(i) > 3])

# words that start with a capital letter
print([i for i in sr if i.istitle()])

# words that end with  g
print([i for i in sr if i.endswith('g')])

"""Python Text Basics(Part 2)(Set functions)"""

s = "To be or not to be, that is the question"

# tokenization
sr = s.split(' ')
print(sr)

# set of unique words
srs = set(sr)
print(srs)

# create set irrespective of capital letters
srs = set([i.lower() for i in sr])
print(srs)

"""Python text basics(part 2.5)(word comparison)"""

# check if sentence starts with, ends with letters
print(s.startswith('T'))
print(s.endswith('n'))

# check if a word is in a sentence
print('s' in s)

# check if a words is in uppercase, lowercase, Title(starts with capital letters)
print(sr[0].isupper())
print(sr[0].islower())
print(sr[0].istitle())

# check if a word is made up of alphabets, digits or both
print('pranha2'.isalpha())
print('pranha2'.isdigit())
print('pranha2'.isalnum())

# make every word into lowercase, uppercase or title
print(s.lower())
print(s.upper())
print(s.title())

# join multiple strings
print(sr[0].join(sr[1]))

# take out spaces from before and after words
print("   aaa     ".strip())
print("    aaa    ".rstrip())

# find words in strings from the front and back
print(s.find("be"))
print(s.rfind("be"))

# replace a word in a string
print(s.replace('be', 'Be'))

"""Python text basics(part 3)(words to characters)"""

s = 'oudougadou'
sr = s.split('ou')
print(sr)

print('ou'.join(sr))

#list of characters
sl = list(s)
print(sl)